---

- name: Cisco show version example
  hosts: all
  gather_facts: false

  tasks:
    - name: Display IOS version info from all inventory devices
      ios_command:
        commands: show version | incl Version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
