---
- name: Configure Cisco IOS device security
  hosts: Routers
  gather_facts: no
  connection: network_cli
  become: yes
  tasks:

    - name: Secure Line Console 0 with a login password of 'cisco'
      cisco.ios.ios_config:
        lines:
          - password cisco
          - login
        parents: line con 0

    - name: Enable service password encryption
      cisco.ios.ios_config:
        lines:
          - service password-encryption

    - name: Set minimum password length to 3
      cisco.ios.ios_config:
        lines:
          - security passwords min-length 3
        state: present


        
