- name: Set login banner
  hosts: all
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Set login banner as specified
      ios_banner:
    #You can change below value to (motd, login, incoming or slip-ppp)
        banner: login
        text: |
          #######################################################
          #                                                     #
          #     Good morning, Charlie or Jon!                   #
          #     Please be sure to switch off SOAC while trying  #
          #     to SSH! It's easy to forget but but will save   #
          #     considerable time!                              #
          #     Also, please remember to wipe the running       #
          #     config after you're done to make things easier  #
          #     for the next person. Good luck!                 #
          #     Thank you!                                      #
          #                                                     #
          #     Charlie                                         #
          #     Network Administrator                           #
          #     $(domain)                                       #
          #                                                     #
          #######################################################
        state: present
#End of codes
